# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI - Lucee 5.4

on: [push, pull_request,workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      luceeVersion: light-6.0.0.300-SNAPSHOT
      luceeVersionQuery: 5.4/all/light

    steps:
    - name: Start MongoDB (docker)
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongodb-version: 4.4
        mongodb-port: 27017
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: lucee-mssql
        restore-keys: |
          ${{ runner.os }}-m2
          maven-cache
    - name: Cache Lucee files
      uses: actions/cache@v4
      with:
        path: _actions/lucee/script-runner/main/lucee-download-cache
        key: lucee-downloads-${{ env.luceeVersion }}
        restore-keys: |
          lucee-downloads
    - name: Build extension-mongodb with Ant
      run: ant -noinput -verbose -buildfile build.xml
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mongodb-lex
        path: dist/*.lex
    - name: Checkout Lucee
      uses: actions/checkout@v4
      with:
        repository: lucee/lucee
        path: lucee
    - name: Run Lucee Test Suite, labels="mongodb"
      uses: lucee/script-runner@main
      with:
        webroot: ${{ github.workspace }}/lucee/test
        execute: /bootstrap-tests.cfm
        luceeVersion: ${{ env.luceeVersion }}
        luceeVersionQuery: ${{ env.luceeVersionQuery }}
        extensionDir: ${{ github.workspace }}/dist
        extensions: 87FE44E5-179C-43A3-A87B3D38BEF4652E # eh-cache extension required
      env:
        testLabels: mongodb
        MONGODB_SERVER: localhost
        MONGODB_PORT: 27017
        MONGODB_DB: lucee
        MONGODB_DATABASE: lucee
